Add support for cert-manager v1.3 Approval conditions
jetstack/google-cas-issuer pull request #34
Opened 2021-04-12 15:48 UTC by jakexks

2021-04-12 15:58 UTC, JoshVanL requested changes
Couple things from me.

/assign @jakexks

2021-04-12 15:58 UTC, JoshVanL commented on config/rbac/cert_manager_controller_approver_clusterrole.yaml
> +  - cas-issuer.jetstack.io/*
Needs to be:

```yaml
  - googlecasclusterissuers.cas-issuer.jetstack.io/*
  - googlecasissuers.cas-issuer.jetstack.io/*
 ```

2021-04-12 15:58 UTC, JoshVanL commented on pkg/controller/certificaterequest/certificaterequest_controller.go
> +			setReadyCondition(cmmeta.ConditionFalse, cmapi.CertificateRequestReasonFailed, msg)
It's been mostly decided that we are going to use a different Ready Reason than Failed https://github.com/jetstack/cert-manager/pull/3878. You might want to wait for v1.3.1 for `cmapi.CertificateRequestReasonDenied`, but you can use anything you want.

2021-04-12 15:58 UTC, JoshVanL commented on pkg/controller/certificaterequest/certificaterequest_controller.go
> +			setReadyCondition(cmmeta.ConditionFalse, cmapi.CertificateRequestReasonFailed, msg)
We should also move this line out of the `disable-approval-check` flag check. We optimistically always check for Denial, but can choose to ignore approval.

2021-04-14 15:52 UTC, jakexks commented
/unassign
/assign @JoshVanL

2021-04-15 09:46 UTC, JoshVanL reviewed
Final thing from me. You may want to hold cancel if you disagree.

/hold 
/lgtm

2021-04-15 09:46 UTC, JoshVanL commented on pkg/controller/certificaterequest/certificaterequest_controller.go
> +		r.Recorder.Event(&certificateRequest, eventTypeWarning, cmapi.CertificateRequestReasonDenied, msg)
I think we shouldn't fire an event if the CR is denied, as the approver should fire an event anyway. Saves a bit of pressure on the API.

2021-04-15 10:20 UTC, JoshVanL commented
/lgtm

2021-04-15 10:22 UTC, jakexks commented
(leaving on hold while I add tests on another branch)

2021-04-20 10:16 UTC, jakexks commented
/hold cancel

2021-04-20 10:19 UTC, merged