Helm Chart fixes
jetstack/google-cas-issuer pull request #86
Opened 2022-10-26 11:49 UTC by milesarmstrong

Two usability fixes for the Helm chart:

- We need to be able to add annotations to the ServiceAccount to enable Workload Identity (Step 7 [here](https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity#authenticating_to))
- The metrics port set in `values.yaml` wasn't being passed to the binary, so it was defaulting to listening on `:8080`

2022-10-26 11:51 UTC, milesarmstrong commented
@JoshVanL would really appreciate if you could release the chart via https://charts.jetstack.io/ as well, we're having to store the unpackaged chart within our wrapper chart and reference it like so currently:

```
dependencies:
- name: cert-manager
  version: 1.8.2
  repository: https://charts.jetstack.io/
- name: cert-manager-google-cas-issuer
  version: 0.6.0
  repository: file://./cert-manager-google-cas-issuer
```

2022-11-01 15:39 UTC, JoshVanL commented
Thanks @milesarmstrong, can you please increase the helm chart version so that it can be released under a different version?

I think you will also need to run `$ ./hack/update-helm-docs.sh`.

2022-11-03 09:36 UTC, milesarmstrong commented
@JoshVanL updated!

2022-11-09 09:32 UTC, milesarmstrong commented
@JoshVanL anything else you need from me to get the merged and released?

2022-11-23 17:37 UTC, milesarmstrong commented
👋 @JoshVanL please can we get this merged?

Also curious if this project is maintained by Jetstack, or just by yourself?

2022-12-13 15:07 UTC, SgtCoDFish commented
Hey @milesarmstrong - sorry it took a while to get back to you on this!

This looks totally reasonable; thank you for raising it!

Unfortunately the tests are gonna fail because of a quirk in how they're set up which doesn't allow them to run against forks. I'll look into running them locally and then I'll look to merge and do a release :+1: 

> Also curious if this project is maintained by Jetstack, or just by yourself?

This project is in theory maintained by Jetstack but is in a bit of a limbo state at the moment without a clear owner so updates are a bit ad-hoc and infrequent - sorry about that! Hopefully should get a bit more clarity next year.

2022-12-13 15:16 UTC, SgtCoDFish requested changes
One little thing, then I'd be happy to merge and try to get a new release out!

2022-12-13 15:16 UTC, SgtCoDFish commented on deploy/charts/google-cas-issuer/Chart.yaml
> +version: v0.6.2
suggestion: could we bump the appVersion to `v0.6.2` too?

Ideally we'd be able to separately release the helm chart in isolation from the underlying application version, but we're not there today. If we could bump the appVersion to match the version, I should be able to do a new release quickly with these changes :+1:

2022-12-13 15:48 UTC, milesarmstrong commented on deploy/charts/google-cas-issuer/Chart.yaml
> +version: v0.6.2
done!

2022-12-13 15:48 UTC, SgtCoDFish commented on deploy/charts/google-cas-issuer/Chart.yaml
> +version: v0.6.2
Thank you!

2022-12-13 15:52 UTC, SgtCoDFish commented
Thanks very much @milesarmstrong  - I'll try to cut a release by the end of the day :+1:

2022-12-13 15:52 UTC, SgtCoDFish approved these changes
/lgtm
/approve

2022-12-13 15:52 UTC, merged

2022-12-14 15:02 UTC, SgtCoDFish commented
@milesarmstrong We've now published v0.6.2 - thanks again!